# Generated by Django 4.0.4 on 2022-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_topic_remove_room_created_room_host_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
