# Generated by Django 4.0.4 on 2022-04-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='create',
            new_name='created',
        ),
    ]
